# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data]
highlighter:      pygments

# Permalinks
permalink:        /posts/:title/

# User Configuration
title:            Christiaan Baaij
tagline:          'Haskell & Hardware'
description:      'Some random Haskell blog'
url:              http://christiaanb.github.io
baseurl:          '/'
paginate:         3
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

# Author Info
author:
  name:           'Christiaan Baaij'
  url:            http://christiaanb.github.io

# Social Integration
social:
  twitter:        ChristiaanBaaij
  disqus:         christiaanbaaij
  addthis_pubid:  ra-5506ca1c2cef566d

# Google Analytics Configuration
# Proxy response must be in JSON and should have the fields - ga:pagePath, ga:pageview
google_analytics:
  tracking_id:      UA-42920604-2
  super_proxy_url:  http://christiaanblog.appspot.com/query?id=ahBzfmNocmlzdGlhYW5ibG9nchULEghBcGlRdWVyeRiAgICAgICACgw&format=json

# Github
github:
  repo:           https://github.com/christiaanb/christiaanb.github.io
  feedback:       https://github.com/christiaanb/christiaanb.github.io/issues

# Version Info
version:          1.0
